// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_PCC3tROvpv6jnRU02vC_JbNa5D6hXzY',
    appId: '1:510080137101:android:6dfd6dd241ce7b62792fc4',
    messagingSenderId: '510080137101',
    projectId: 'project-regiment8112',
    storageBucket: 'project-regiment8112.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm9x81myrboXlNRBDuzsEvRefKypWBtKs',
    appId: '1:510080137101:ios:67cf18d1dce37570792fc4',
    messagingSenderId: '510080137101',
    projectId: 'project-regiment8112',
    storageBucket: 'project-regiment8112.appspot.com',
    androidClientId: '510080137101-bcnc1ds7jehvci53je36n2v18jtssstu.apps.googleusercontent.com',
    iosClientId: '510080137101-b4hsosrfa194cr9u2ts5luns4biut4i2.apps.googleusercontent.com',
    iosBundleId: 'com.regiment.regiment8112',
  );
}
